### ISSUE TITLE
Sobre ./referencias/README.md

### ISSUE THREAD

**Issue by penserbjorne** [gwolf/clase-sistop-2017-01#136]
Quisiera saber si es posible añadir referencias sobre este archivo por nuestra y cual seria el proceso.
¿Solo las añadimos y solicitamos el PR? ¿ Hay que seguir alguna linea de formato?

De una vez, me gustaria añadir estos dos links para lo comentado en clase.
- [Breve explicacion de DirtyC0w](http://www.sectorx.com.ar/dirtyc0w-una-condicion-carrera-desde-11-anos-permite-hacerse-root/)
- [Explicacion de DirtyC0w en video](https://www.youtube.com/watch?v=kEsshExn7aE)

Saludos

**Comment by gwolf** [comment]
¡Me parece genial! Sí, yo pensaba en la sección de "referencias" como un espacio para dejarles material para que ustedes aprovechen... Pero si tienes algo que puedas compartir con los demás, ¡por favor hazlo por esa vía!
