### ISSUE TITLE
Fuentes no disponibles

### ISSUE THREAD

**Issue by penserbjorne** [gwolf/clase-sistop-2017-01#87]
Los enlaces desde la presentación a las siguientes fuentes no están disponibles:
- De gatos y ratones:  http://www.eecs.harvard.edu/~mdw/course/cs161/assign/asst1.html
- Interseccion de caminos: http://www.eecs.harvard.edu/~mdw/course/cs161/assign/asst1.html
- El cruce del rio: http://greenteapress.com/semaphores/downey08semaphores.pdf
- Santa Claus: http://greenteapress.com/semaphores/downey08semaphores.pdf

Disponibles:
- El elevador: http://alumni.cs.ucsb.edu/~zoran/cs170/project1.html
- Los alumnos y el asesor: http://alumni.cs.ucsb.edu/~zoran/cs170/project1.html

**Comment by gwolf** [comment]
¡Ups! Mis presentaciones están envejeciendo :-( Tengo que ponerme las pilas y re-ilustrarlas. ¡Gracias por avisar! Lo reviso... Tan pronto pueda :-(

**Comment by gwolf** [comment]
..."Tan pronto pueda"... ¡No tengo perdón!
Bueno... Por fin hice la corrección en mis láminas (por lo menos, antes de iniciar el siguiente semestre). Y por fin puedo cerrar este *issue*. ¡Gracias!
